### ISSUE TITLE
Random crash with the Dryads [1.16.5]

### ISSUE THREAD

**Issue by Yoshun** [skyjay1/GreekFantasy#102]
Hi,

I have a server with a lot of mods and we can play several hours without any problem but sometimes the server crashes and the first mod mentioned is Greek Fantasy.
Is it possible to have a fix if the problem comes from this mod ?

Last crash-report : https://pastebin.com/SR7dV7G6
Forge : 1.16.5-36.2.39
Greek Fantasy : 16.5.5

Thanks :)

**Comment by skyjay1** [comment]
The crash has something to do with `HurtByTargetGoal` but the Dryad uses the default Minecraft version of that goal. The problem is likely one of the mixins that affects that goal. (Possibly Botania or Charm) (or Random Patches, Astral Sorcery, Infernal Expansion, Expandability, Quark, Whisperwoods, Upgrade Aquatic, Endergetic, Artifacts, Abnormals Core, Relics, Resourceful Bees, or Structure Gel, all of which are mentioned on line 9 of the crash report)

**Comment by Yoshun** [comment]
Okay I see !
A side effect of another mod possibly, difficult to fix this I imagine.
It's not blocking anyway so we'll deal with it.
Thank you for your answer, I let you close the issue :)
