### ISSUE TITLE
Port to 1.21?

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#147]
Hey!
2 years ago I used play this mod on 1.19.2 religiously before I took a break, I'm planning to came back to Minecraft again, but was wondering if it would be possible to port this mod to 1.21? It would be nice to load my world with all the greek fantasy stuff in 1.21, it's such a legendary mod. 
Hope you've been well!

**Comment by skyjay1** [comment]
Hello again Looodon, I started to port RPG Gods to 1.20.1, the "gods and favor" library that Greek Fantasy uses. However progress has since taken a backseat because modding doesn't pay the bills. I'm starting a new job and may or may not have time/energy/funds to work on mods like this one and Nomadic Tents, would love to bring them to NeoForge but we will see.

**Comment by Looodon** [comment]
Surprised you remember me! It's perfectly fine, I downgraded to 1.20.1 cuz I realized there's barely any mods on 1.21. I'll close this suggestion because I don't want this project to feel like you have things piling up as it should be for fun and not a chore. Also I totally understand, whether you work on it or not I wish you good luck on your new job! Have a great day!
