### ISSUE TITLE
Boss spawning causing game to lock up.

### ISSUE THREAD

**Issue by DoCharlcate** [skyjay1/GreekFantasy#38]
Okay this is a weird one. Whenever I ventured near a savanna that was close by to a desert, the game would lock up (mobs froze, chests couldn't be interacted with, items/blocks were not dropping etc), and it resulted in a hard reset to fix.  This was happening to me in both 1.16.4 and 1.16.5. 

Anyway today, I started a new mod pack and loaded all the mods one by one, started a new world with each mod and flew to find dessert/savannah biomes to see if I could find the culprit and Greek Fantasy seems to be it. I noticed this time also it happened just as the Medusa boss spawned in but not sure If that is connected to the savanna/desert issue which seems to be a constant. 

I don't have a crash log as I had to hard reset everytime which to my knowledge does not produce a crash log but here is my mod list of the newest pack if helps.. 

abnormals core
autumnity
buzzier bees
charm
curios
cyclopscore
druidcraft
dungeons plus
earth mobs mod
eidolon
elemental craft
evil craft
forbidden arcanus
greek fantasy
jei
natures compass
patchouli
quark
savage and ravage
structure gel
upgrade aquatic

**Comment by skyjay1** [comment]
Thanks for reporting this, I'll look into it. Does this happen with *only* Greek Fantasy? Or is it a mod incompatibility of some sort?
I have had people report crashes who happened to also be running Abnormal Core and Quark. Another person reported a crash with an AI improvement mod that tried to mess with the Medusa's AI (probably since she carries a bow).
