### ISSUE TITLE
'your high favor earned you blessing from...' spam

### ISSUE THREAD

**Issue by kubistonek** [skyjay1/GreekFantasy#41]
the 'your high favor earned you blessing from...' message keeps appearing every ~30 minutes for no reason

**Comment by skyjay1** [comment]
Yes... that's because a favor effect was triggered on the player. The message is not spam, it's there so you know why you suddenly have a potion effect or an extra emerald or something.

**Comment by Febilian** [comment]
I'm inclined to believe this might actually be an issue - I have also been getting this message CONSTANTLY like clockwork on a dedicated server. It's only ever with Hades even if I have high favor with other deities(in this case, Hera or Hermes).

The reason I think this is a bug rather than intended behavior is because I never seem actually get any in-game effects accompanying the chat messages; certainly none of the things that seem detailed in the data files of the mod, going by the source. No items, no summoned entities, no potion effects. It's _possible_ that there is an effect being triggered every single time that is simply not immediately obvious, but I find it difficult to believe that with me carefully checking both my inventory and surroundings every time I get the message, I am missing its function every single time.

It is worth mentioning that I _am_ running a slightly older version of the mod - `16.4.15` - because of the unregistered nemean lion den feature issue and me not wanting to compromise other mod worldgen while waiting for a fix - but unless this behavior was specifically addressed with the newer version's data pack format changes, it probably still happens on `16.4.16` as well.



This next bit is a suggestion that is directly relevant to this:

- Have the message that's sent to player because of a favor effect hint at what the favor effect was rather than a generic "deity did something because of high/low favor" message, like "Hades has blessed you with [item name] as thanks for your actions" or "Hades incurs his wrath against you, summoning [monster name]", etc. It would both make it easier to troubleshoot deity favor effects and provide more clarity for what it's actually doing for the player.

Alternatively, maybe have a config option so players can choose whether they want this message in their chat or above their hotbar as a toast(similar to bed sleeping eligibility messages). This would allow the player to still see a message about it while they're playing, but it wouldn't fill up the chat.

**Comment by skyjay1** [comment]
The most recent release of Greek Fantasy allows you to turn off blessing messages or move them to the HUD instead of chat. I'm not sure why the effects are not appearing to work, but it could be a client-server desync because favor effects run server-side only.
